#!/usr/local/bin/ansible-playbook
---
- name: Install Docker
  hosts: localhost
  become: true
  connection: local
  tasks:

    - name: Install OS packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Get GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Add APT repo x86_64
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_facts['distribution_release'] }} stable"
      when: ansible_machine == "x86_64"

    - name: Add APT repo aarch64
      apt_repository:
        repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_facts['distribution_release'] }} stable"
      when: ansible_machine == "aarch64"

    - name: Create config folder
      file:
        path: /etc/docker
        state: directory

    - name: Setup daemon.json file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "bip": "192.168.127.5/24",
            "default-address-pools": [
              {
                "base": "192.168.128.0/17",
                "size": 24
              }
            ]
          }

    - name: Install Docker packages
      apt:
        update_cache: True
        name: '{{ item }}'
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: True
