#!/usr/local/bin/ansible-playbook
---
- name: Install Docker
  hosts: localhost
  connection: local
  vars:
    docker_compose_version: v2.14.0

  tasks:

    - name: Install OS packages
      apt:
        update_cache: True
        name: '{{ item }}'
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Get GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Add APT repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"

    - name: Create config folder
      file:
        path: /etc/docker
        state: directory

    - name: Setup daemon.json file
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "40m",
              "max-file": "100",
              "compress": "true"
            },
            "bip": "192.168.127.5/24",
            "default-address-pools": [
              {
                "base": "192.168.128.0/17",
                "size": 24
              }
            ]
          }

    - name: Install Docker packages
      apt:
        update_cache: True
        name: '{{ item }}'
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: True

    - name: Get the docker-compose binary
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
