#!/usr/local/bin/ansible-playbook
---
- name: Install Hashicorp tools
  hosts: localhost
  connection: local

  tasks:
  - name: Install gpg package
    package:
      name: gpg

  - name: Get GPG key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present

  - name: Add APT repo
    apt_repository:
      repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"

  - name: Install tools
    apt:
      update_cache: True
      name: '{{ item }}'
    loop:
      - packer
      - terraform
      - vault

  - name: Download Terraform Docs
    command: curl -L "https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz" -o "terraform-docs.tar.gz"
    args:
      chdir: /tmp
      creates: /tmp/terraform-docs.tar.gz

  - name: Extract terraform-docs.tar.gz
    command: tar -C /usr/local/bin --no-same-owner -zxf terraform-docs.tar.gz terraform-docs
    args:
      chdir: /tmp
      creates: /usr/local/bin/terraform-docs

