---
- name: Install Kubernetes tools
  hosts: my_hosts

  vars:
    kubernetes_version: 1.28.1

  tasks:
    - name: Install pre-req packages
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: True
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

    - name: Install Kubernetes repo key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: Install Kuberentes repo
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
        state: present
        filename: kubernetes

    - name: Install kubectl package
      apt:
        name: '{{ item }}={{ kubernetes_version }}-00'
        update_cache: True
        allow_downgrades: True
      loop:
        - kubectl

    - name: Hold the installed kubectl package to prevent upgrades
      dpkg_selections:
        name: '{{ item }}'
        selection: hold
      loop:
        - kubectl
