---
- name: Install Kubernetes tools
  hosts: my_hosts

  vars:
    kubectl_arm64_url: https://distro.eks.amazonaws.com/kubernetes-1-29/releases/8/artifacts/kubernetes/v1.29.1/bin/linux/arm64/kubectl
    kubectl_amd64_url: https://distro.eks.amazonaws.com/kubernetes-1-29/releases/8/artifacts/kubernetes/v1.29.1/bin/linux/amd64/kubectl

  tasks:
    - name: Install pre-req packages
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: True
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg

    - name: Install kubectl
      get_url:
        url: "{{ kubectl_arm64_url }}"
        dest: /usr/bin/kubectl
        mode: 0755
      when: ansible_machine == "aarch64"

    - name: Install kubectl
      get_url:
        url: "{{ kubectl_amd64_url }}"
        dest: /usr/bin/kubectl
        mode: 0755
      when: ansible_machine == "amd64"
