---
- name: Install Tailscale
  hosts: my_hosts

  tasks:
    - name: Install pre-req packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - gpg

    - name: Install GPG key
      apt_key:
        url: https://pkgs.tailscale.com/stable/debian/{{ ansible_facts['distribution_release'] }}.noarmor.gpg

    - name: Install APT repo x86_64
      apt_repository:
        repo: deb [arch=amd64] https://pkgs.tailscale.com/stable/debian {{ ansible_facts['distribution_release'] }} main
      when: ansible_machine == "x86_64"

    - name: Install APT repo aarch64
      apt_repository:
        repo: deb [arch=arm64] https://pkgs.tailscale.com/stable/debian {{ ansible_facts['distribution_release'] }} main
      when: ansible_machine == "aarch64"

    - name: Install Tailscale
      apt:
        update_cache: True
        name: tailscale
        state: latest
