#!/usr/local/bin/ansible-playbook
---
- name: Install Hashicorp Terraform
  hosts: localhost
  connection: local

  tasks:

    - name: Install OS packages
      package:
        name: '{{ item }}'
        state: present
      loop:
        - gnupg
        - software-properties-common

    - name: Get GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add APT repo
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"

    - name: Install Terraform
      apt:
        update_cache: True
        name: terraform

